### ISSUE TITLE
Support necessary calls to run truffle tests

### ISSUE THREAD

**Issue by vgrichina** [near/near-web3-provider#10]
Looks like we are missing such calls typically involved in truffle tests execution:
- `evm_revert`
- `evm_snapshot`
- `eth_getLogs`

Looks like revert/snapshot is most challenging to implement as we don't have this feature at nearcore level. I see at least such options however:
- we can be creating ephemeral nearcore runtime for every test, like e.g. now we have mock context for AssemblyScript https://github.com/nearprotocol/wasm-mock-vm.
- we can implement snapshot/revert inside of EVM contract. Not sure how hard it is within current implementation.

**Comment by barbaraliau** [comment]
@emaG3m do you know if we can implement the snapshot/revert inside the EVM contract or if that's been done?

**Comment by emaG3m** [comment]
> @emaG3m do you know if we can implement the snapshot/revert inside the EVM contract or if that's been done?

This has not been done, and I don't believe the contract has any test-specific functionality, so that would be entirely new. @prestwich could maybe speak to it more. Given that we're winding down, supporting this test functionality that near itself doesn't yet support, seems kind of big in scope since we're still finishing up some of the core functionality. Probably possible for future devs to implement if they'd like.

**Comment by prestwich** [comment]
I don't think we can reasonably support this without one of the following:
1. near node support
2. a `ganache`-like simulated near node

Either of those are going to be outside the scope here :thinking: 

As far as testing goes, using `ganache` without the near provider should be sufficient for testing solidity in almost all cases

**Comment by ilblackdragon** [comment]
Generally, truffle tests work now with precompiles outside of revert/snapshot functionality which is not supported by nearcore.

Will create a separate issue when those things will be needed.
